version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sketchai
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgressql

volumes:
  db:
